-- Drill 09 — Multi-Join Analytical Patterns: Unmatched relationship analysis
-- Business question: Which customers have orders that have not yet shipped, and what shipper information is available for those orders?
-- Expected output: customer_id, company_name, order_id, shipper_name, shipped_date
-- Notes: preserve the order rows even when shipping details are missing or the order has not shipped yet
-- Tables used: Customers, Orders, Shippers
