-- Drill 07 — Multi-Join Analytical Patterns: Pre-aggregate before a join
-- Business question: What is the total revenue for each order once customer and shipper information is attached?
-- Expected output: order_id, customer_id, shipper_name, order_total
-- Notes: compute one row per order first, then join to Customers and Shippers
-- Tables used: "Order Details", Orders, Customers, Shippers
