-- Drill 03 — INSERT, UPDATE & DELETE: Insert from a SELECT
-- Business question: How would you populate a target table from an existing query result instead of hand-writing row values?
-- Expected outcome: an INSERT ... SELECT statement that copies or transforms rows into a target table
-- Notes: this is a good place to move rows from a raw staging table into a cleaned table
-- Tables used: raw_customers, clean_customers
