-- Drill 05 — Multi-Join Warmup: Enriched order lines
-- Business question: What product and category does each order line belong to?
-- Expected output: order_id, product_id, product_name, category_name, quantity
-- Notes: start from order_details, then join products and categories
-- Tables used: order_details, products, categories
