-- Drill 04 — Multi-Join Warmup: Product suppliers
-- Business question: Which supplier provides each product?
-- Expected output: product_id, product_name, supplier_id, supplier_name
-- Notes: join Products to Suppliers
-- Tables used: Products, Suppliers
