-- Drill 02 — Multi-Join Warmup: Order lines
-- Business question: What line items belong to each order?
-- Expected output: order_id, order_date, product_id, quantity, unit_price
-- Notes: join Orders to "Order Details" and keep one row per order line
-- Tables used: Orders, "Order Details"
