-- Drill 04 — Window Functions: RANK() vs DENSE_RANK()
-- Business question: How do product rankings differ when ties are handled with RANK() versus DENSE_RANK()?
-- Expected output: product_id, total_quantity, sales_rank, dense_sales_rank
-- Notes: aggregate sold quantity per product first, then compare the two ranking functions; keep the window ORDER BY on total_quantity only if you want ties to remain tied
-- Tables used: order_details
