-- Drill 01 — Window Functions: ROW_NUMBER() over all orders
-- Business question: What sequence number does each order have when all orders are sorted by order_date?
-- Expected output: order_id, customer_id, order_date, row_num
-- Notes: use ROW_NUMBER() without PARTITION BY; break same-day ties with order_id
-- Tables used: orders
