-- Drill 03 — Window Functions: Latest order per customer
-- Business question: Which is the most recent order for each customer?
-- Expected output: customer_id, order_id, order_date
-- Notes: rank orders from newest to oldest, using order_date DESC and order_id DESC, then filter after ranking
-- Tables used: orders
